version: 1.0.{build}
branches:
  only:
  - master
  - dev
skip_tags: true
matrix:
  fast_finish: true 
image: Visual Studio 2017
environment:
  azure-service-bus-dotnet/ClientSecret:
    secure: yO+qgkyY5FO/4a7rMRl60F5eMTrz03L6r3oD/VCzgKhtuYW5APmgvd9Wu+AHM8T7
  azure-service-bus-dotnet/TenantId:
    secure: qHryGNZnkslfefQBj8zMZPNhrxSuoe1NJVauNidhhvVLTGi194jotblSTmExuTKQ
  azure-service-bus-dotnet/AppId:
    secure: sTox3GxT9oqRUhCe56citfJdYQmdUVMaZlAevCJ0xnC0nV9LyR8+gC/I4Ji/FKoU
  matrix:
    # First build
    - DotNetRunTime: netcoreapp1.0
      azure-service-bus-dotnet/CodeCovSecret:
        secure: m5MmSzWEul80WJWHp+aznaNNgbQpIYcYfSTBNcPMWO2qgPmTls0OjXezx1KoJGTi
    # Second build
    - DotNetRunTime: net46
      azure-service-bus-dotnet/SkipCodeCoverage: true
skip_commits:
  files:
    - '**/*.md'
artifacts:
- path: .\build\artifacts\*
build_script:
- ps: .\build\build.ps1
test: off
